update function names
a2s .get_info(), .get_players() and .get_rules() changed to .info(), .players() and .rules() .
Prior to this change, python manage.py update_game_info would result in `AttributeError: 'ServerQuerier' object has no attribute 'get_info'`